### ISSUE TITLE
Proposed documentation overhaul

### ISSUE THREAD

**Issue by bardiharborow** [haraka/haraka.github.com#10]
Hey @baudehlo! I'm from the @twbs team. I recently noticed that your documentation is running an old version of Bootstrap (v3.1.0) as well as underutilizing the Jekyll engine (e.g. duplicated header code in all your top-level pages). If you'd be interested, I'm happy to provide a pull request for the following (I'm half-way there already, just trying to untangle my work into reviewable commits):

- [ ] Use Jekyll layouts for top-level pages instead of `template.html`.
- [ ] Update Bootstrap to v4.1.0 and make adjustments for relevant breaking changes.
- [ ] Reimplement navigation using a `_data/navigation.yaml` file rather than using perl to generate a sidebar directly.
- [ ] Modernize the design (possibly to look something more like [this](https://getbootstrap.com/docs/4.2/getting-started/introduction/)).
- [ ] Remove unused files and generally freshen the code base.

**Comment by baudehlo** [comment]
Oh god this would be wonderful. The docs are in much need of an overhaul.
Thanks!

**Comment by msimerson** [comment]
closed, to match #11
