### ISSUE TITLE
List of plugins has a few "Haraka"s

### ISSUE THREAD

**Issue by PAStheLoD** [haraka/haraka.github.com#4]
For example https://github.com/haraka/haraka.github.com/blob/master/manual/Plugins.html#L138 and https://github.com/haraka/haraka.github.com/blob/master/manual.html#L138

Maybe using a common file for menu and including that via JS could help with maintainability too? (See http://mozilla.github.io/nunjucks/, or http://harpjs.com/ which has partials and github pages support.)

**Comment by hatsebutz** [comment]
mkpages.pl, line 87 reads:
my ($title) = ($output =~ /<h1>([^<]*)/);

changing to:
my ($foo, $title) = ($output =~ /<h1>(<[^>]*>)?([^<]*)/);

should fix this.

**Comment by msimerson** [comment]
no longer relevant
